export enum ROUTES {
    MAIN = '/',
    NEW = '/newest',
    NEWS = '/news',
    POST = '/news/:id',
    PAST = '/past',
    COMMENTS = '/comments',
    ASK = '/ask',
    SHOW = '/show',
    JOBS = '/jobs',
    SUBMIT= '/submit',
    USER = '/user',
    LOGIN = '/login',
    REGISTER = '/register',
}